name: Enable Folder on EC2

on:
  workflow_dispatch:

jobs:
  rename-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the user is allowed
        run: |
          allowed_users=("TShreyas93" "allowed_user_2" "allowed_user_3")
          if [[ ! " ${allowed_users[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
            echo "You are not authorized to run this workflow."
            exit 1
          fi
          echo "Running workflow for ${{ github.actor }}"
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Rename folder on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          MY_PASS: ${{ secrets.EC2_HOST }}
        run: |
          echo $MY_PASS
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            # Navigate to the project directory
            mv /tmp/Trigger/Auto_DISBLED /tmp/Trigger/Auto
            sh /tmp/Trigger/Auto/Display.sh 
          EOF
